// Load .env from root before importing db
try {
	// eslint-disable-next-line @typescript-eslint/no-var-requires
	require("dotenv").config({ path: require("path").resolve(__dirname, "../../.env") });
} catch (e) {
	// ignore if dotenv is not installed
}

import { db } from "@/src/index"; // Adjust path if needed
import { products } from "./schema";

const sampleProducts = [
	// --- MEN ---
	{
		name: "Sauvage",
		slug: "dior-sauvage",
		brand: "Dior",
		price: "145.00",
		stock: 50,
		gender: "men",
		isTrending: true,
		description: "A radically fresh composition, dictated by a name that has the ring of a manifesto.",
		imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3b/Dior_Sauvage_Verpackung.jpg",
		scentNotes: { top: ["Calabrian bergamot", "Pepper"], middle: ["Sichuan Pepper", "Lavender"], base: ["Ambroxan", "Cedar"] },
	},
	{
		name: "Bleu de Chanel",
		slug: "bleu-de-chanel",
		brand: "Chanel",
		price: "138.00",
		stock: 40,
		gender: "men",
		isTrending: true,
		description: "A woody, aromatic fragrance for the man who defies convention.",
		imageUrl: "https://images.unsplash.com/photo-1530630458144-014709e10016?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Lemon", "Mint"], middle: ["Ginger", "Nutmeg"], base: ["Incense", "Vetiver"] },
	},
	{
		name: "Acqua Di Gio",
		slug: "acqua-di-gio",
		brand: "Giorgio Armani",
		price: "98.00",
		stock: 100,
		gender: "men",
		isTrending: false,
		description: "A fresh and aquatic fragrance, capturing the simple perfection of the sea.",
		imageUrl: "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Lime", "Lemon"], middle: ["Sea Notes", "Peach"], base: ["White Musk", "Oakmoss"] },
	},
	{
		name: "Eros",
		slug: "versace-eros",
		brand: "Versace",
		price: "92.00",
		stock: 60,
		gender: "men",
		isTrending: false,
		description: "Sublime divinity, the new perfume for men by Versace.",
		imageUrl: "https://images.unsplash.com/photo-1616787884784-5f5c357778b4?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Mint", "Green Apple"], middle: ["Tonka Bean", "Ambroxan"], base: ["Vanilla", "Cedar"] },
	},
	{
		name: "Aventus",
		slug: "creed-aventus",
		brand: "Creed",
		price: "435.00",
		stock: 15,
		gender: "men",
		isTrending: true,
		description: "The exceptional Aventus was inspired by the dramatic life of a historic emperor.",
		imageUrl: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Pineapple", "Bergamot"], middle: ["Birch", "Patchouli"], base: ["Musk", "Oakmoss", "Vanilla"] },
	},
	{
		name: "1 Million",
		slug: "paco-rabanne-1-million",
		brand: "Paco Rabanne",
		price: "102.00",
		stock: 80,
		gender: "men",
		isTrending: false,
		description: "A spicy-leather scent that has the power to be bewitching. Insolent leather and amber.",
		imageUrl: "https://images.unsplash.com/photo-1512777576244-b846ac3d816f?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Blood Mandarin", "Peppermint"], middle: ["Rose Absolute", "Cinnamon"], base: ["Leather Accord", "Amber"] },
	},
	{
		name: "Terre d'Hermès",
		slug: "hermes-terre-d-hermes",
		brand: "Hermès",
		price: "118.00",
		stock: 40,
		gender: "men",
		isTrending: false,
		description: "A symbolic narrative exploring material and its metamorphosis.",
		imageUrl: "https://images.unsplash.com/photo-1622353387799-d4588e174249?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Orange", "Grapefruit"], middle: ["Pepper", "Pelargonium"], base: ["Vetiver", "Cedar", "Patchouli"] },
	},
	{
		name: "Spicebomb Extreme",
		slug: "viktor-rolf-spicebomb-extreme",
		brand: "Viktor&Rolf",
		price: "130.00",
		stock: 35,
		gender: "men",
		isTrending: true,
		description: "A hotter interpretation of the original fragrance that is more explosive and seductive.",
		imageUrl: "https://images.unsplash.com/photo-1620050519363-2f0996c56834?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Grapefruit", "Pimento"], middle: ["Cinnamon", "Cumin"], base: ["Tobacco", "Amber", "Black Vanilla"] },
	},
	{
		name: "Y Eau de Parfum",
		slug: "ysl-y-edp",
		brand: "Yves Saint Laurent",
		price: "128.00",
		stock: 65,
		gender: "men",
		isTrending: true,
		description: "A deep, fresh and masculine fragrance. Created for the man who dares to follow his passions.",
		imageUrl: "https://images.unsplash.com/photo-1557121655-f55dbb5c2a11?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Apple", "Ginger"], middle: ["Sage", "Juniper Berries"], base: ["Amber Wood", "Tonka Bean"] },
	},
	{
		name: "L'Homme",
		slug: "prada-l-homme",
		brand: "Prada",
		price: "108.00",
		stock: 55,
		gender: "men",
		isTrending: false,
		description: "A fragrance of pairs, of doubles, of juxtapositions and layers.",
		imageUrl: "https://images.unsplash.com/photo-1623376046908-4e8929f9dfec?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Neroli", "Pepper"], middle: ["Iris", "Amber", "Violet"], base: ["Patchouli", "Cedar"] },
	},
	{
		name: "The One for Men",
		slug: "dg-the-one-men",
		brand: "Dolce & Gabbana",
		price: "96.00",
		stock: 90,
		gender: "men",
		isTrending: false,
		description: "An elegant, sensual perfume that is decidedly modern but also a unique, timeless classic.",
		imageUrl: "https://images.unsplash.com/photo-1578996530663-b26a5753b754?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Grapefruit", "Coriander"], middle: ["Ginger", "Orange Blossom"], base: ["Tobacco", "Amber"] },
	},
	{
		name: "Explorer",
		slug: "montblanc-explorer",
		brand: "Montblanc",
		price: "98.00",
		stock: 75,
		gender: "men",
		isTrending: false,
		description: "An invitation to a fantastic journey, an irresistible call for adventure.",
		imageUrl: "https://images.unsplash.com/photo-1605618825227-8898144075b9?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Bergamot", "Pink Pepper"], middle: ["Leather", "Vetiver"], base: ["Cocoa Pod", "Patchouli"] },
	},
	{
		name: "Wanted by Night",
		slug: "azzaro-wanted-by-night",
		brand: "Azzaro",
		price: "105.00",
		stock: 45,
		gender: "men",
		isTrending: true,
		description: "The fragrance of a modern-day seducer. An explosive woody-oriental-spicy scent.",
		imageUrl: "https://images.unsplash.com/photo-1590736969955-71cc94801759?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Cinnamon", "Mandarin"], middle: ["Red Cedar", "Cumin"], base: ["Tobacco", "Cypress"] },
	},
	{
		name: "Code Parfum",
		slug: "armani-code-parfum",
		brand: "Giorgio Armani",
		price: "140.00",
		stock: 30,
		gender: "men",
		isTrending: true,
		description: "Strong and sensitive, Code Parfum rewrites the codes of a timeless masculine fragrance.",
		imageUrl: "https://images.unsplash.com/photo-1621453284067-17b0769d6519?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Bergamot", "Bergamot Leaf"], middle: ["Iris", "Clary Sage"], base: ["Tonka Bean", "Cedar"] },
	},

	// --- WOMEN ---
	{
		name: "Black Opium",
		slug: "ysl-black-opium",
		brand: "Yves Saint Laurent",
		price: "130.00",
		stock: 85,
		gender: "women",
		isTrending: true,
		description: "The highly addictive feminine fragrance from Yves Saint Laurent.",
		imageUrl: "https://images.unsplash.com/photo-1594035910387-fea4779426e9?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Pear", "Pink Pepper"], middle: ["Coffee", "Jasmine"], base: ["Vanilla", "Patchouli"] },
	},
	{
		name: "Flowerbomb",
		slug: "viktor-rolf-flowerbomb",
		brand: "Viktor&Rolf",
		price: "142.00",
		stock: 45,
		gender: "women",
		isTrending: true,
		description: "An explosive floral bouquet. A host of sweet and floral notes.",
		imageUrl: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Tea", "Bergamot"], middle: ["Orchid", "Rose"], base: ["Patchouli", "Musk"] },
	},
	{
		name: "Daisy",
		slug: "marc-jacobs-daisy",
		brand: "Marc Jacobs",
		price: "106.00",
		stock: 120,
		gender: "women",
		isTrending: false,
		description: "Charming simple. Daisy transports you to a place that is optimistic, beautiful, and pure.",
		imageUrl: "https://images.unsplash.com/photo-1615160057038-163255153289?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Violet Leaf", "Grapefruit"], middle: ["Violet", "Gardenia"], base: ["Musk", "White Woods"] },
	},
	{
		name: "Miss Dior",
		slug: "miss-dior",
		brand: "Dior",
		price: "135.00",
		stock: 30,
		gender: "women",
		isTrending: false,
		description: "A hymn to love, emblematic of Dior femininity with a Couture spirit.",
		imageUrl: "https://images.unsplash.com/photo-1592914610354-fd354ea45e48?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Italian Mandarin"], middle: ["Rose", "Jasmine"], base: ["Musk", "Patchouli"] },
	},
	{
		name: "No. 5",
		slug: "chanel-no-5",
		brand: "Chanel",
		price: "160.00",
		stock: 50,
		gender: "women",
		isTrending: false,
		description: "The very essence of femininity. A powdery floral bouquet housed in an iconic bottle.",
		imageUrl: "https://images.unsplash.com/photo-1595867275464-92984b54e8db?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Aldehydes", "Ylang-Ylang"], middle: ["Jasmine", "Rose"], base: ["Vanilla", "Sandalwood"] },
	},
	{
		name: "La Vie Est Belle",
		slug: "lancome-la-vie-est-belle",
		brand: "Lancôme",
		price: "118.00",
		stock: 100,
		gender: "women",
		isTrending: true,
		description: "Make your life even more beautiful with Lancôme’s new feminine fragrance.",
		imageUrl: "https://images.unsplash.com/photo-1590509890483-3760490b7e28?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Blackcurrant", "Pear"], middle: ["Iris", "Jasmine"], base: ["Praline", "Vanilla", "Patchouli"] },
	},
	{
		name: "Good Girl",
		slug: "carolina-herrera-good-girl",
		brand: "Carolina Herrera",
		price: "124.00",
		stock: 70,
		gender: "women",
		isTrending: true,
		description: "A sensual, evocative fragrance born of the beautiful contradictions of modern women.",
		imageUrl: "https://images.unsplash.com/photo-1550524514-ad245199684b?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Almond", "Coffee"], middle: ["Jasmine Sambac", "Tuberose"], base: ["Tonka Bean", "Cacao"] },
	},
	{
		name: "Bloom",
		slug: "gucci-bloom",
		brand: "Gucci",
		price: "138.00",
		stock: 60,
		gender: "women",
		isTrending: true,
		description: "Capturing the spirit of the contemporary, diverse and authentic women of Gucci.",
		imageUrl: "https://images.unsplash.com/photo-1582211594533-268f4f1edcb9?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Rangoon Creeper"], middle: ["Jasmine Bud"], base: ["Tuberose"] },
	},
	{
		name: "Alien",
		slug: "mugler-alien",
		brand: "Mugler",
		price: "120.00",
		stock: 45,
		gender: "women",
		isTrending: false,
		description: "The daughter of the Sun, human and divine, Alien is a talisman fragrance.",
		imageUrl: "https://images.unsplash.com/photo-1610461888750-10bfc601b874?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Sambac Jasmine"], middle: ["Cashmeran Wood"], base: ["White Amber"] },
	},
	{
		name: "Sì Eau de Parfum",
		slug: "armani-si",
		brand: "Giorgio Armani",
		price: "130.00",
		stock: 55,
		gender: "women",
		isTrending: false,
		description: "At once chic, voluptuous, intense, and soft, Sì lingers on the skin and enchants the senses.",
		imageUrl: "https://images.unsplash.com/photo-1616787680008-8dfd82a13c9e?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Blackcurrant Nectar"], middle: ["Freesia", "Rose of Mai"], base: ["Musk", "Vanilla", "Patchouli"] },
	},
	{
		name: "Chloé Eau de Parfum",
		slug: "chloe-edp",
		brand: "Chloé",
		price: "115.00",
		stock: 90,
		gender: "women",
		isTrending: false,
		description: "A light and fresh yet seductively strong and self-possessed scent.",
		imageUrl: "https://images.unsplash.com/photo-1594122230689-45899d9e6f69?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Peony", "Lychee"], middle: ["Rose", "Magnolia"], base: ["Cedar", "Amber"] },
	},
	{
		name: "Bright Crystal",
		slug: "versace-bright-crystal",
		brand: "Versace",
		price: "95.00",
		stock: 110,
		gender: "women",
		isTrending: false,
		description: "Sheer sensuality, crystal transparency, and luminous brightness.",
		imageUrl: "https://images.unsplash.com/photo-1515688594390-b649af70d282?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Yuzu", "Pomegranate"], middle: ["Peony", "Lotus"], base: ["Acajou", "Musk"] },
	},
	{
		name: "Black Orchid",
		slug: "tom-ford-black-orchid",
		brand: "Tom Ford",
		price: "150.00",
		stock: 35,
		gender: "women",
		isTrending: true,
		description: "A luxurious and sensual fragrance of rich, dark accords and an alluring potion of black orchids.",
		imageUrl: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Truffle", "Blackcurrant"], middle: ["Black Orchid", "Spices"], base: ["Mexican Chocolate", "Patchouli"] },
	},
	{
		name: "English Pear & Freesia",
		slug: "jo-malone-english-pear",
		brand: "Jo Malone",
		price: "144.00",
		stock: 65,
		gender: "women",
		isTrending: true,
		description: "The essence of autumn. The sensuous freshness of just-ripe pears is wrapped in a bouquet of white freesias.",
		imageUrl: "https://images.unsplash.com/photo-1615592398457-873b27b3d9d3?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["King William Pear"], middle: ["Freesia"], base: ["Patchouli"] },
	},

	// --- UNISEX ---
	{
		name: "Santal 33",
		slug: "le-labo-santal-33",
		brand: "Le Labo",
		price: "215.00",
		stock: 15,
		gender: "unisex",
		isTrending: true,
		description: "A defining image of the spirit of the American West with all that it implies.",
		imageUrl: "https://images.unsplash.com/photo-1585218356057-dc2cda5a5d09?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Violet Accord", "Cardamom"], middle: ["Iris", "Ambrox"], base: ["Cedarwood", "Leather", "Sandalwood"] },
	},
	{
		name: "Gypsy Water",
		slug: "byredo-gypsy-water",
		brand: "Byredo",
		price: "190.00",
		stock: 25,
		gender: "unisex",
		isTrending: true,
		description: "An ode to the beauty of Romani culture, its unique customs, intimate beliefs and distinguished way of living.",
		imageUrl: "https://images.unsplash.com/photo-1617306020586-778263155799?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Bergamot", "Lemon", "Pepper"], middle: ["Incense", "Pine Needles"], base: ["Amber", "Vanilla", "Sandalwood"] },
	},
	{
		name: "CK One",
		slug: "calvin-klein-ck-one",
		brand: "Calvin Klein",
		price: "65.00",
		stock: 200,
		gender: "unisex",
		isTrending: false,
		description: "A naturally clean, pure, and contemporary fragrance with a refreshing new point of view.",
		imageUrl: "https://images.unsplash.com/photo-1584307567786-077d2062f6b8?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Pineapple", "Green Notes"], middle: ["Nutmeg", "Violet"], base: ["Sandalwood", "Amber"] },
	},
	{
		name: "Tobacco Vanille",
		slug: "tom-ford-tobacco-vanille",
		brand: "Tom Ford",
		price: "275.00",
		stock: 10,
		gender: "unisex",
		isTrending: false,
		description: "Opulent. Warm. Iconic. Reminiscent of an English Gentleman’s Club.",
		imageUrl: "https://images.unsplash.com/photo-1594035910387-fea4779426e9?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Tobacco Leaf", "Spices"], middle: ["Tonka Bean", "Tobacco Flower"], base: ["Dried Fruits", "Woody Notes"] },
	},
	{
		name: "Baccarat Rouge 540",
		slug: "mfk-baccarat-rouge-540",
		brand: "Maison Francis Kurkdjian",
		price: "325.00",
		stock: 20,
		gender: "unisex",
		isTrending: true,
		description: "Luminous and sophisticated, Baccarat Rouge 540 lays on the skin like an amber, floral and woody breeze.",
		imageUrl: "https://images.unsplash.com/photo-1592914610354-fd354ea45e48?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Jasmine", "Saffron"], middle: ["Amberwood"], base: ["Fir Resin", "Cedar"] },
	},
	{
		name: "Oud Wood",
		slug: "tom-ford-oud-wood",
		brand: "Tom Ford",
		price: "275.00",
		stock: 18,
		gender: "unisex",
		isTrending: true,
		description: "Rare. Exotic. Distinctive. One of the most rare, precious, and expensive ingredients in a perfumer’s arsenal.",
		imageUrl: "https://images.unsplash.com/photo-1585218356057-dc2cda5a5d09?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Rosewood", "Cardamom"], middle: ["Oud Wood", "Sandalwood"], base: ["Tonka Bean", "Amber"] },
	},
	{
		name: "Philosykos",
		slug: "diptyque-philosykos",
		brand: "Diptyque",
		price: "175.00",
		stock: 30,
		gender: "unisex",
		isTrending: false,
		description: "The memory of a Greek summer at Mount Pelion. A hymn to the fig tree.",
		imageUrl: "https://images.unsplash.com/photo-1615592398457-873b27b3d9d3?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Fig Leaf", "Fig"], middle: ["Coconut", "Green Notes"], base: ["Cedar", "Fig Tree"] },
	},
	{
		name: "Jazz Club",
		slug: "maison-margiela-jazz-club",
		brand: "Maison Margiela",
		price: "145.00",
		stock: 45,
		gender: "unisex",
		isTrending: true,
		description: "A heady cocktail of cigars and leather, recreating the atmosphere of a Brooklyn jazz club.",
		imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Pink Pepper", "Lemon"], middle: ["Rum", "Sage"], base: ["Tobacco Leaf", "Vanilla Bean"] },
	},
	{
		name: "Bal d'Afrique",
		slug: "byredo-bal-d-afrique",
		brand: "Byredo",
		price: "190.00",
		stock: 25,
		gender: "unisex",
		isTrending: true,
		description: 'Focusing on beauty and fantasy, Bal d’Afrique is Ben Gorham’s "love letter" to Africa.',
		imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Bergamot", "Lemon", "Neroli"], middle: ["Violet", "Jasmine"], base: ["Black Amber", "Musk", "Vetiver"] },
	},
	{
		name: "Mojave Ghost",
		slug: "byredo-mojave-ghost",
		brand: "Byredo",
		price: "190.00",
		stock: 22,
		gender: "unisex",
		isTrending: false,
		description: "A woody composition inspired by the soulful beauty of the Mojave Desert.",
		imageUrl: "https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Ambrette", "Nesberry"], middle: ["Magnolia", "Sandalwood"], base: ["Cedarwood", "Musk"] },
	},
	{
		name: "Wood Sage & Sea Salt",
		slug: "jo-malone-wood-sage",
		brand: "Jo Malone",
		price: "144.00",
		stock: 60,
		gender: "unisex",
		isTrending: false,
		description: "Escape the everyday along the windswept shore. Alive with the mineral scent of the rugged cliffs.",
		imageUrl: "https://images.unsplash.com/photo-1616787884784-5f5c357778b4?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Ambrette Seeds"], middle: ["Sea Salt"], base: ["Sage"] },
	},
	{
		name: "Dark Rum",
		slug: "malin-goetz-dark-rum",
		brand: "Malin+Goetz",
		price: "96.00",
		stock: 80,
		gender: "unisex",
		isTrending: false,
		description: "Inspired by the old world bay rum used by sailors traveling through the Caribbean.",
		imageUrl: "https://images.unsplash.com/photo-1590736939955-71cc94801759?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Bergamot", "Plum"], middle: ["Rum", "Leather"], base: ["Amber", "Patchouli", "Milk"] },
	},
	{
		name: "Tacit",
		slug: "aesop-tacit",
		brand: "Aesop",
		price: "130.00",
		stock: 35,
		gender: "unisex",
		isTrending: false,
		description: "A crisp, green, and citrus fragrance. Tacit is at once familiar in its citrus notes and distinctly contemporary.",
		imageUrl: "https://images.unsplash.com/photo-1629198688000-71f23e745b6e?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Yuzu", "Basil"], middle: ["Rosemary", "Mint"], base: ["Cedar", "Vetiver", "Amber"] },
	},
	{
		name: "Thé Noir 29",
		slug: "le-labo-the-noir-29",
		brand: "Le Labo",
		price: "215.00",
		stock: 12,
		gender: "unisex",
		isTrending: true,
		description: "An ode to the noble leaf and the craft that surrounds it. A deep and fresh scent.",
		imageUrl: "https://images.unsplash.com/photo-1582211594533-268f4f1edcb9?auto=format&fit=crop&w=800&q=80",
		scentNotes: { top: ["Fig", "Bay Leaf"], middle: ["Cedar", "Vetiver"], base: ["Black Tea", "Tobacco"] },
	},
];

async function main() {
	console.log("🌱 Seeding products...");

	// Optional: Clear existing products to avoid duplicates
	// await db.delete(products);

	for (const product of sampleProducts) {
		await db.insert(products).values(product).onConflictDoNothing();
	}

	console.log("✅ Seeding complete!");
	process.exit(0);
}

main().catch((err) => {
	console.error("❌ Seeding failed:", err);
	process.exit(1);
});
